### ISSUE TITLE
viprea.org down, contact e-mail no longer valid

### ISSUE THREAD

**Issue by mgorny** [viprea/viprea-overlay#1]
Hello,

Both the `@oscailtfoundation.org.uk` e-mail address (from Gentoo repositories.xml) and the `@viprea.org` e-mail address (from github) are down. Please provide a valid contact e-mail address for the overlay ASAP, and register a bugs.gentoo.org account with the same address.

**Comment by aoibhinnditori** [comment]
gentoo@aoibh.in

**Comment by mgorny** [comment]
Updated, thanks. You may also want to update the e-mail on viprea github page.
